# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2315c4e7037379002dac14e7ef95e0d6"
name = "Delivery Dates"
application_url = "https://chuug-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://chuug-app-production.up.railway.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://chuug-app-production.up.railway.app/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://chuug-app-production.up.railway.app/webhooks/orders-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://chuug-app-production.up.railway.app/api/auth" ]
