# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2315c4e7037379002dac14e7ef95e0d6"
name = "chuug"
application_url = "http://127.0.0.1:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_orders , write_orders"

[auth]
redirect_urls = [ "http://127.0.0.1:3000/api/auth" ]
